### ISSUE TITLE
Missing text-domain for string translations

### ISSUE THREAD

**Issue by bahiirwa** [codepotent/Update-Manager#21]
# Description
When I run the pre-hooks for building my plugin, I throws a warning for these lines in 
`classes/class-wc-update-client.php` specifically L182-184. 

```
// This will make the jQuery below work with various languages.
$text1 = esc_html__('Compatible up to:');
$text2 = esc_html__('Reviews');
$text3 = esc_html__('Read all reviews');
```

Was this intentional to have `esc_html__` with a missing text domain?

**Comment by johnalarcon** [comment]
Hi Laurence, good eye! The text domain hasn't been forgotten; these are actually the core texts, so, they don't require a text domain. :)

**Comment by johnalarcon** [comment]
On further consideration, I'm re-opening this issue. I see no harm in simply adding the text domain. It won't break anything and, well, it's only 3 strings. I'll get this into the 1.0.0 final release, which I anticipate in another week or so, just to be sure no further issues roll in.

**Comment by xxsimoxx** [comment]
I think you should consider it. If you add text domain to "core" texts, they will not be translated. Never, because strings in UpdateClient.class.php for being translated need to have `my-text-domain` as text domain (when used not for Update Manager itself).

The [line](https://github.com/codepotent/Update-Manager/blob/6f540b7697f0c74870f3270dea53276bb263c383/classes/UpdateClient.class.php#L337) that adds the "View details" link, where there is `codepotent-update-manager` as text domain (and a typo, it should be `esc_html__` and not `esc_html`) for me creates inconsistent UX in the plugin page.

![image](https://user-images.githubusercontent.com/29772709/71729462-15fe6680-2e40-11ea-8a87-f0d349c9eeb3.png)

**Comment by johnalarcon** [comment]
> The line that adds the "View details" link, where there is codepotent-update-manager as text domain (and a typo, it should be esc_html__ and not esc_html) for me creates inconsistent UX in the plugin page.

Thanks, @xxsimoxx, for the additional information. Please open a dedicated issue for this part as it is different that the issue initially raised. I just don't want it to become lost in the mix. 😄

**Comment by johnalarcon** [comment]
It seems I originally didn't comprehend what Simone was trying to say above. As he correctly points out, adding a text domain to the update client texts actually breaks the core translation functionality. In light of this, the text domain will be re-removed.

For those who have trouble with builds or sniffs, just add your own text domain to the client file – the same domain that you're using in your plugin.
