### ISSUE TITLE
Strange look in View Details

### ISSUE THREAD

**Issue by xxsimoxx** [codepotent/Update-Manager#27]
# Description 
Too many space when using H2 (##)
Naming the section "FAQ" results in the word "faq" to be displayed.
You can see those in the screenshots.

# Steps to Reproduce
1. Use the plugin-details.txt in a plugin

[plugin-details.txt](https://github.com/codepotent/Update-Manager/files/4046285/plugin-details.txt)

# Screenshots
<img width="512" alt="Schermata 2020-01-10 alle 15 59 54" src="https://user-images.githubusercontent.com/29772709/72163357-02b14500-33c4-11ea-91d6-71ccce391de9.png">
<img width="508" alt="Schermata 2020-01-10 alle 16 02 50" src="https://user-images.githubusercontent.com/29772709/72163368-05ac3580-33c4-11ea-9e25-3469729cd208.png">

# Additional Context
I can not understand if it is about Parsedown, but I've tried the [latest beta](plugin-details.txt) and there is no difference.

Really not important!

**Comment by johnalarcon** [comment]
It's actually a core thing... I've been unable to determine what the spacing is accounting for. Due to this, I did not "correct" it since it wasn't clear if it might break something else.

The "solution" here is to not use the markdown for `h2` tags. The way I've done my own listings is to use h1's at the top of each view...and to use h3/h4/h5/ under that when I need subsections.

### For Description view, I used only the h1
![image](https://user-images.githubusercontent.com/12477319/72168369-e2609680-3381-11ea-8afb-53273421dc1f.png)

### Other views use h1 at the and h3/h4/h5 under that (if needed):
![image](https://user-images.githubusercontent.com/12477319/72168455-0e7c1780-3382-11ea-8f95-1c60106833ea.png)

**Comment by xxsimoxx** [comment]
Same solution I've used! Thank you for checking!
