### ISSUE TITLE
Use of WP_PLUGIN_URL may prevent scripts from loading

### ISSUE THREAD

**Issue by timbocode** [codepotent/Update-Manager#30]
# Description 
On a site using https, WP_PLUGIN_URL (as used in includes/constants.php) could potentially prevent scripts such as post-edit.js from loading. This will only happen as a result of user error, i.e. if the `siteurl` (Settings > General) is set to http instead of https. WP_PLUGIN_URL returns the `siteurl` and makes no adjustment for https.

# Steps to Reproduce
1. Use a https site e.g. **https**://www.example.com
2. Go to Settings > General and set `siteurl` to http e.g. **http**://www.example.com
3. In update manager, edit any endpoint
4. You should see that the font is not set to monospace in the textarea and that the links don't work.

# Expected Behavior
Font should be monospace and links should work.

# Screenshots
![image](https://user-images.githubusercontent.com/4199514/72892862-83026f00-3d0f-11ea-8db4-b5e8fec07799.png)

![image](https://user-images.githubusercontent.com/4199514/72893177-569b2280-3d10-11ea-8396-15b8e319ec4b.png)

# Additional Context
Using `plugins_url()` should get around this problem.

**Comment by johnalarcon** [comment]
I'm unable to recreate in Firefox or Chrome. I _think_ it is due to your own browser settings. By default, all the major browsers block insecure content on secure sites, so, if you want to use a mix of HTTP and HTTPs (mixed content), you'll have to disable that option in your browser, else it will be blocked.

Here's a screen capture after following the steps you listed; the Update Manager script (and font family) are working properly

**Chrome**
![image](https://user-images.githubusercontent.com/12477319/72928934-b8a65880-3d0d-11ea-8b40-85d613a1c1af.png)

**Firefox**
![image](https://user-images.githubusercontent.com/12477319/72929465-babce700-3d0e-11ea-852b-3b4d0f128f92.png)

**More Info**

https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content

https://www.howtogeek.com/443032/what-is-mixed-content-and-why-is-chrome-blocking-it/

**Comment by johnalarcon** [comment]
> This will only happen as a result of user error, i.e. if the siteurl (Settings > General) is set to http instead of https. WP_PLUGIN_URL returns the siteurl and makes no adjustment for https.

When you place a URL in that field, you don't want the system making assumptions about the protocol; it should simply be obeyed as-is (like how it currently works). Because browsers are taking a more restrictive approach to mixed content, the end user must disable this setting (in their browser) if they want to use mixed content. The "fix" here is to adjust the browser settings.

**Comment by timbocode** [comment]
You seem to be using `localhost` in which case I doubt there'll be any mixed content.

I can reproduce this every time in Firefox and Chrome on Windows and Linux just using the default settings. I realise the issue is dependent on browser settings and what would essentially be user error but it's not an inconceivable situation.

Just trying to help. Not a criticism. All I am saying is that this could _potentially_ be an issue for which there is an easy workaround.

**Comment by timbocode** [comment]
>When you place a URL in that field, you don't want the system making assumptions about the protocol; it should simply be obeyed as-is (like how it currently works).

A very likely scenario is that a user updates their site to https using cPanel or whatever but forgets to update the siteurl fields. Very easily done and very possible. Nothing to do with browsers.

**Comment by johnalarcon** [comment]
> A very likely scenario is that a user updates their site to https using cPanel or whatever but forgets to update the siteurl fields. Very easily done and very possible. Nothing to do with browsers.

Looks like we were cross-posting. I don't take the issue as criticism. No worries. PS. I do use SSL on localhost.

I see your point about _how_ this might occur, however, this is an edge-case user error for which there are already 2 solutions: undo the protocol edit that broke it, or change the browser settings to allow mixed content. The Update Manager plugin is written to honor the correct values (the constants); if I circumvented this, the plugin would be overstepping its role.

**Comment by johnalarcon** [comment]
If I _did_ change the code in the plugin, it wouldn't solve the issue in any other plugins that used the constant. If you're concerned this may become problematic, you can use the [plugins_url](https://developer.wordpress.org/reference/hooks/plugins_url/) filter to make sure they match prior to serving the page – this would remove the potential for the issue from all avenues, rather than handling it in a piecemeal approach.

`apply_filters( 'plugins_url', $url, $path, $plugin );`

**Comment by johnalarcon** [comment]
I'd like to follow-up with this more carefully; when you have a few minutes, please see my DM on Slack.

**Comment by johnalarcon** [comment]
Re-opening this issue as an enhancement to be implemented.

**Comment by johnalarcon** [comment]
Changed `WP_PLUGIN_URL` in the `constants.php` file to use `plugins_url()`. The constants.php file has been revised across all Code Potent projects to address this issue at the root level.
