### ISSUE TITLE
Feature request: one update check for many plugins by same author

### ISSUE THREAD

**Issue by zigpress** [codepotent/Update-Manager#52]
# Description
If there are a number of plugins on one site, all using the Update Manager class, all from the same plugin author, and all making their update check to the same Update Manager installation, it would be great if there was a way for one update check to be made, instead of many, for speed reasons. As far as I can see, this is not currently the case, and a separate check is made by each plugin.

# Context
It will be a while before CP v2 is released (the one with the plugin directory), so for now any solution to this probably lies within the Update Manager plugin's codebase.
I realise any solution may not necessarily be easy but I just wanted to put the question "out there" to see if there may be some ingenious way of doing this.
Maybe there could be a way for plugins with the Update Manager class to register themselves in the options table and then the invocation of the update check process would get intercepted and use that data to send a "multi-plugin" JSON request. It could store transients of last update check to avoid repeated checks, or something like that. Not sure if it's that simple since I'm a bit hazy on the update process built into core.

Happy to discuss this on Slack/Forums/here/elsewhere if you'd like.

**Comment by johnalarcon** [comment]
> ...it would be great if there was a way for one update check to be made, instead of many, for speed reasons.

I, too, am a sucker for speed...and is the main reason why I prioritized the performance enhancements that went out in v 2.0.0 (along with theme support) instead of kicking them down the line. 👍 

> As far as I can see, this is not currently the case, and a separate check is made by each plugin.

Correct; the core makes an individual request for each plugin.

> I realise any solution may not necessarily be easy but I just wanted to put the question "out there" to see if there may be some ingenious way of doing this.

I appreciate that you thought it out a bit in your request; it's quite more involved than it seems on the surface. And I'm sure there's some ingenious way to do it, however, given that very few users would ever need this functionality, I'd be unable to justify the time expenditure to figure it out and implement it. Update Manager was built in the name of _necessity_, rather than of _innovation_; it won't likely see any substantive new code outside of compatibility or bug fixes.

When the official directory comes out, you might raise this same feature request there. It's a good idea, for sure. Unfortunately, I can't point to a time frame on that; it's been roadblocked for months and attempts of getting information (or pitching in) have been rebuffed. ¯\\\_(ツ)\_/¯

**Comment by zigpress** [comment]
Fair enough, and thanks for the detailed reply. Looks like some lobbying vis-a-vis the plugin directory might be in order :-)
