### ISSUE TITLE
Wrong "tested up to" value

### ISSUE THREAD

**Issue by xxsimoxx** [codepotent/Update-Manager#60]
# Description 

Seems that the "tested up to" values relies on an option that is no more set.
[Here](https://github.com/codepotent/Update-Manager/blob/734b4ac3d8241e26a6aaabcdeb0344cf3410b6a4/classes/UpdateClient.class.php#L106) the value is set from an option that is never set, but just deleted in main plugin uninstall process.

# Steps to Reproduce
1. Go to plugins page and get more info about a plugin using UpdateClient

# Expected Behavior
Tested up to should show 1.2.0

# Screenshots
![image](https://user-images.githubusercontent.com/29772709/118842211-49bd1d80-b8c9-11eb-9272-9b2448f2fea9.png)
manually changed option...

**Comment by xxsimoxx** [comment]
Sorry it's a duplicate of #55. Closing.

**Comment by johnalarcon** [comment]
Since the fix involves `UpdateClient.class.php`, it will have to be a major version bump to 3.0.0. It would be nice to push a major version with some neat new features...but virtually no feature requests have come in at all, so, I've been hesitant on doing a major release for a tiny bugfix. If you're super annoyed by it, I can get it on my schedule. :) Also, thanks for proactively closing this issue.

**Comment by xxsimoxx** [comment]
No, really is not a problem!
But if I'm not misunderstanding semver, you have not to bump version as you don't change any filter or similar, but it's just a bugfix.

**Comment by johnalarcon** [comment]
:) You're not misunderstanding. In this case, any change to the update client file is considered breaking as it requires end users to push a new client file out into their plugins to the fix to be applied. ie, a simple update of the (UM) plugin does not resolve the issue.
